import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Appbar from "./components/ui/Appbar"; // Your Appbar component
import Providers from "./providers";
import { ReactNode } from "react";
import Sidebar from "./components/main/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "TrashAI - A conversational todo list app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-zinc-900 text-white`}
      >
        <Providers>
          {/* <Appbar /> */}
    
          <main className="pt- h-screen flex flex-col">
            {/* <Sidebar /> */}
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}